# Generated by Django 6.0 on 2026-04-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0030_trickentry_pending_term_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionproposal',
            name='base_content_md',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='revisionproposal',
            name='base_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='revisionproposal',
            name='base_title',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='revisionproposal',
            name='base_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
