# Generated by Django 6.0 on 2026-04-14 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0032_competitionnotice_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_article_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueticket',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issueticket',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issueticket',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_issue_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trickentry',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trickentry',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trickentry',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trick_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tricktermsuggestion',
            name='review_note',
            field=models.TextField(blank=True),
        ),
    ]
